#!/usr/bin/env python3

import sys
import argparse
import logging
import rtmidi
import rtmidi.midiutil
from miditools.udpmidi import MidiServer
from miditools.portconf import MidiPortPairArray


def main_loop(srv, ports):

    # setup input handler
    for port_num, midi_in in ports.get_midi_in_ports():
        def cb(msg_time, data):
            midi_in_handler(msg_time, srv, port_num)
        midi_in.set_callback(cb)
        midi_in.ignore_types(sysex=False)

    while(True):
        try:
            # get next message
            pkt, port = srv.recv()
            # some stats
            lost_pkts = srv.get_lost_pkts()
            if lost_pkts:
                logging.warning("lost packets: %d", lost_pkts)
            # forward
            port_num = pkt.get_port_num()
            midi_out = ports.get_midi_out(port_num)
            if not midi_out:
                logging.warning("#%d: Port unknown!: %s", port_num, pkt)
            elif pkt.is_sysex():
                sysex = pkt.get_sysex()
                logging.debug("#%d: RX(sysex): %s -> %s", port_num, pkt, sysex)
                midi_out.send_message(sysex)
            else:
                msg = pkt.get_msg()
                tup = msg.get_tuple()
                logging.debug("#%d: RX: %s -> %s", port_num, pkt, tup)
                midi_out.send_message(tup)
        except KeyboardInterrupt:
            logging.info("shutting down...")
            break


def midi_in_handler(msg_time, srv, port_num):
    raw_msg, time = msg_time
    # is sysex?
    if raw_msg[0] == 0xf0:
        sysex = bytes(raw_msg)
        pkt = srv.send_sysex(port_num, sysex)
        logging.debug("#%d: TX(sysex): %s -> %s", port_num, sysex, pkt)
    else:
        pkt = srv.send_raw_msg(port_num, raw_msg)
        logging.debug("#%d: TX: %s -> %s", port_num, raw_msg, pkt)


def list_ports():
    rtmidi.midiutil.list_input_ports()
    rtmidi.midiutil.list_output_ports()


DESC = "transfer Midi data between Midi UDP and a local Midi port"
LOG_FORMAT = '%(asctime)-8s.%(msecs)03d   %(levelname)-7s  %(message)s'
TIME_FORMAT = "%H:%M:%S"


def main():
    # parse args
    parser = argparse.ArgumentParser(description=DESC)
    parser.add_argument('-p', '--ports', nargs='+', default=[],
                        help='Define midi port pair: midi_in:midi_out[+] '
                        'Repeat for multiple ports.')
    parser.add_argument('-l', '--list-ports', action='store_true',
                        help='List all input and output ports')
    parser.add_argument('-v', '--verbose', action='store_true',
                        help="verbose output")
    parser.add_argument('-d', '--debug', action='store_true',
                        help="enabled debug output")
    parser.add_argument('-s', '--server',
                        help="host addr of UDP server. default=localhost:6820",
                        default="localhost")
    parser.add_argument('-c', '--client',
                        help="host addr of UDP client. default=localhost:6821",
                        default="localhost")
    opts = parser.parse_args()

    # setup logging
    level = logging.WARNING
    if opts.debug:
        level = logging.DEBUG
    elif opts.verbose:
        level = logging.INFO
    logging.basicConfig(level=level, format=LOG_FORMAT, datefmt=TIME_FORMAT)

    # list ports
    if opts.list_ports:
        list_ports()
        return 0

    # midi ports
    ports = MidiPortPairArray()
    for port in opts.ports:
        ports.parse_port_pair_from_str(port)

    num_ports = ports.get_num_ports()
    if num_ports == 0:
        logging.error("No midi ports defined! Use '-p' option. Aborting...")
        return 1

    # open server
    srv = MidiServer.parse_from_str(opts.server, opts.client)
    host_addr, peer_addr = srv.get_host_and_peer_addr()
    logging.info("host_addr: %s", host_addr)
    logging.info("peer_addr: %s", peer_addr)

    # main loop
    return main_loop(srv, ports)


if __name__ == '__main__':
    sys.exit(main())
