#!/usr/bin/env python3

from miditools.udpmidi import UDPServer

with UDPServer() as s:
    print("midi-udp-echo: waiting for data on {}".format(s))

    my_seq = 1
    while(True):
        pkt, addr = s.recv()
        print("recv from", addr, ":", pkt)

        # check seq num
        seq_num = pkt.get_seq_num()
        if my_seq != pkt.get_seq_num():
            print("SEQ_NUM wrong: got={}, want={}".format(seq_num, my_seq))
        my_seq += 1

        # echo reply
        s.send(pkt, addr)
